'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import {LiquidGlass,LiquidGlassButton} from '@/components/LiquidGlass'
const sb=createClient('https://ktukmjscopggkzrkgnzp.supabase.co','sb_publishable_6NWrr2xGApSApIjQ0irtvA_U05ZQlFX',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})
const sys=()=>sb.schema('aureka_system')
type Room={id:number;code?:string;name:string;is_active?:boolean}
type Profile={user_id:string;full_name:string;email:string|null;primary_room_id:number|null;role_id:string|null;is_active:boolean}
type Role={id:string;code:string;name:string}
export default function GeneralSettings({profile,role,rooms}:{profile:any;role:string|null;rooms:Room[]}){
 const [section,setSection]=useState<'menu'|'general'|'users'>('menu'),[tab,setTab]=useState<'profile'|'units'|'appearance'|'security'>('profile'),[me,setMe]=useState<any>({...profile}),[users,setUsers]=useState<Profile[]>([]),[roles,setRoles]=useState<Role[]>([]),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[theme,setTheme]=useState(()=>typeof window==='undefined'?'light':localStorage.getItem('aureka-theme')||'light')
 const isAdmin=role==='ADMIN'
 const loadUsers=async()=>{if(!isAdmin)return;const {data,error}=await sys().rpc('admin_list_user_profiles');if(error)setMsg(error.message);else setUsers((data||[]) as Profile[])}
 useEffect(()=>{sys().from('app_roles').select('id,code,name').eq('is_active',true).order('name').then(({data})=>setRoles(data||[]));loadUsers()},[isAdmin])
 const saveMe=async()=>{setBusy(true);setMsg('');const {error}=await sys().from('user_profiles').update({full_name:me.full_name,primary_room_id:me.primary_room_id?Number(me.primary_room_id):null}).eq('user_id',profile.user_id);setBusy(false);setMsg(error?'Gagal: '+error.message:'Profil berhasil disimpan.')}
 const toggleTheme=(v:string)=>{setTheme(v);localStorage.setItem('aureka-theme',v);document.documentElement.dataset.theme=v;setMsg('Preferensi tampilan disimpan di perangkat ini.')}
 const filtered=useMemo(()=>users.filter(u=>{const q=search.toLowerCase().trim();return !q||[u.full_name,u.email||''].join(' ').toLowerCase().includes(q)}),[users,search])
 const updateUser=async(u:Profile,patch:Partial<Profile>)=>{setBusy(true);setMsg('');const {error}=await sys().rpc('admin_update_user_profile',{p_user_id:u.user_id,p_full_name:patch.full_name??u.full_name,p_primary_room_id:patch.primary_room_id??u.primary_room_id,p_role_id:patch.role_id??u.role_id,p_is_active:patch.is_active??u.is_active});setBusy(false);if(error)setMsg(error.message);else{setMsg('Perubahan pengguna disimpan.');loadUsers()}}
 return <div style={{display:'grid',gap:14}}>
  {section==='menu'&&<LiquidGlass style={{padding:14}}>
   <div className="eyebrow">PENGATURAN</div><h3 style={{margin:'4px 0 6px',fontSize:24}}>Pengaturan AUREKA</h3>
   <p style={{margin:0,color:'var(--muted)',fontSize:11}}>Pilih area pengaturan. Konfigurasi domain tetap berada di masing-masing kontainer.</p>
   <div className="placeholderGrid" style={{marginTop:14}}>
    <button className="placeholderCard glassPanel" onClick={()=>setSection('general')}><span style={{fontSize:24}}>⚙️</span><b>Pengaturan Umum</b><span>Profil, tampilan, preferensi, unit dan keamanan akun.</span></button>
    <button className="placeholderCard glassPanel" onClick={()=>isAdmin&&setSection('users')} disabled={!isAdmin} style={!isAdmin?{opacity:.55,cursor:'not-allowed'}:undefined}><span style={{fontSize:24}}>👥</span><b>Manajemen User / PIC Pelaporan</b><span>{isAdmin?'Kelola pengguna, role, unit utama, dan status akun.':'Khusus Super Admin.'}</span></button>
   </div>
  </LiquidGlass>}
  {section!=='menu'&&<button className="textButton" onClick={()=>setSection('menu')}>← Kembali ke Pengaturan</button>}
  {section==='general'&&<LiquidGlass style={{padding:14}}><div className="eyebrow">PENGATURAN UMUM</div><h3 style={{margin:'4px 0 6px',fontSize:22}}>AUREKA Settings</h3><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}>{([['profile','Akun Saya'],['units','Unit & Instalasi'],['appearance','Tampilan'],['security','Keamanan']] as const).map(([k,n])=><button key={k} className={tab===k?'textButton navActive':'textButton'} onClick={()=>setTab(k)}>{n}</button>)}</div></LiquidGlass>}
  {section==='users'&&isAdmin&&<LiquidGlass style={{padding:14}}><div className="eyebrow">MANAJEMEN USER</div><h3 style={{margin:'4px 0 6px',fontSize:22}}>User / PIC Pelaporan</h3></LiquidGlass>}
  {msg&&<div className="msg visible">{msg}</div>}
  {section==='general'&&tab==='profile'&&<LiquidGlass style={{padding:14}}><h4>Akun Saya</h4><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label className="field"><span>Nama lengkap</span><input value={me.full_name||''} onChange={e=>setMe({...me,full_name:e.target.value})}/></label><label className="field"><span>Email</span><input value={me.email||''} disabled/></label><label className="field"><span>Role</span><input value={role||'—'} disabled/></label><label className="field"><span>Unit utama</span><select value={me.primary_room_id||''} onChange={e=>setMe({...me,primary_room_id:e.target.value})}><option value="">Belum dipetakan</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><div style={{marginTop:12}}><LiquidGlassButton onClick={saveMe} disabled={busy}>Simpan Profil</LiquidGlassButton></div></LiquidGlass>}
  {section==='users'&&isAdmin&&<LiquidGlass style={{padding:14}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',flexWrap:'wrap'}}><div><h4 style={{margin:'0 0 3px'}}>Manajemen Pengguna</h4><span style={{fontSize:10,color:'var(--muted)'}}>Administrasi profil, role, unit, dan status AUREKA.</span></div><input placeholder="Cari nama / email…" value={search} onChange={e=>setSearch(e.target.value)} style={{maxWidth:240}}/></div><div style={{display:'grid',gap:8,marginTop:12}}>{filtered.map(u=><div key={u.user_id} style={{padding:11,border:'1px solid rgba(20,34,27,.08)',borderRadius:15}}><div style={{display:'grid',gridTemplateColumns:'1.4fr 1fr 1fr auto',gap:8,alignItems:'center'}}><div><b style={{fontSize:11}}>{u.full_name}</b><div style={{fontSize:9,color:'var(--muted)'}}>{u.email||'—'}</div></div><select value={u.primary_room_id||''} onChange={e=>updateUser(u,{primary_room_id:e.target.value?Number(e.target.value):null})}><option value="">Unit belum dipetakan</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select value={u.role_id||''} onChange={e=>updateUser(u,{role_id:e.target.value||null})}><option value="">Role belum dipetakan</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="textButton" onClick={()=>updateUser(u,{is_active:!u.is_active})}>{u.is_active?'Nonaktifkan':'Aktifkan'}</button></div></div>)}</div></LiquidGlass>}
  {section==='general'&&tab==='units'&&<LiquidGlass style={{padding:14}}><h4>Unit & Instalasi</h4><p style={{fontSize:10,color:'var(--muted)'}}>Daftar ini membaca langsung public.master_rooms, sumber yang sama dengan dropdown unit saat Sign Up. Tidak ada master unit kedua di Pengaturan Umum.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:7}}>{rooms.map((r,i)=><div key={r.id} style={{padding:9,border:'1px solid rgba(20,34,27,.08)',borderRadius:13}}><b style={{fontSize:10}}>{String(i+1).padStart(2,'0')} · {r.name}</b><div style={{fontSize:8,color:'var(--muted)'}}>{r.code||('ROOM-'+r.id)} · Aktif</div></div>)}</div></LiquidGlass>}
  {section==='general'&&tab==='appearance'&&<LiquidGlass style={{padding:14}}><h4>Tampilan & Preferensi</h4><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label className="field"><span>Tema</span><select value={theme} onChange={e=>toggleTheme(e.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="field"><span>Bahasa</span><select defaultValue="id"><option value="id">Bahasa Indonesia</option><option value="en">English</option></select></label></div><p style={{fontSize:9,color:'var(--muted)',marginTop:10}}>Preferensi tampilan disimpan lokal agar tidak mengganggu konfigurasi modul.</p></LiquidGlass>}
  {section==='general'&&tab==='security'&&<LiquidGlass style={{padding:14}}><h4>Keamanan</h4><div style={{display:'grid',gap:8,fontSize:11}}><div><b>Authentication:</b> Supabase Auth</div><div><b>Session:</b> Persisted session + auto refresh</div><div><b>Authorization:</b> Role + unit scope</div><div><b>Password:</b> Dikelola oleh Supabase Auth, bukan oleh halaman Pengaturan.</div></div></LiquidGlass>}
 </div>
}
