'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@supabase/supabase-js'
import {LiquidGlass,LiquidGlassButton} from '@/components/LiquidGlass'
const sb=createClient('https://ktukmjscopggkzrkgnzp.supabase.co','sb_publishable_6NWrr2xGApSApIjQ0irtvA_U05ZQlFX',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})
const grainLabel:any={patient_episode:'Per pasien / episode',provider_day:'Dokter × hari',daily_metric:'Metrik harian',event:'Per kejadian',activity:'Per aktivitas',aggregate:'Periode agregat'}
const coreFor=(g:string)=>g==='patient_episode'?{record_date:'',patient_name:'',medical_record_no:'',diagnosis:'',dpjp:'',status:''}:g==='provider_day'?{record_date:'',doctor:'',clinic:'',waiting_minutes:''}:g==='daily_metric'?{record_date:'',service_stream:'',numerator:'',denominator:'',notes:''}:g==='event'?{record_date:'',event_id:'',description:''}:{record_date:'',activity:'',numerator:'',denominator:'',notes:''}
export default function QualityIndicatorWorkspace({initialRoomId,rooms,isAdmin}:{initialRoomId:number|null;rooms:any[];isAdmin:boolean}){
 const [year,setYear]=useState(2026),[roomId,setRoomId]=useState(initialRoomId??rooms[0]?.id??null),[profiles,setProfiles]=useState<any[]>([]),[records,setRecords]=useState<any[]>([]),[core,setCore]=useState<any>(coreFor('activity')),[sel,setSel]=useState<any>({}),[msg,setMsg]=useState('')
 const load=async()=>{if(!roomId)return;const p=await sb.from('aureka_quality.indicator_profiles').select('*').eq('profile_year',year).eq('room_id',roomId).eq('status','published').eq('is_active',true).order('code');const r=await sb.from('aureka_quality.quality_records').select('*').eq('profile_year',year).eq('room_id',roomId).neq('status','archived').order('created_at',{ascending:false});if(p.error||r.error){setMsg((p.error||r.error)?.message||'Gagal memuat data');return}setProfiles(p.data||[]);setRecords(r.data||[]);setCore(coreFor(p.data?.[0]?.measurement_grain||'activity'))}
 useEffect(()=>{load()},[roomId,year])
 const grain=profiles[0]?.measurement_grain||'activity'
 const save=async()=>{const {data:{user}}=await sb.auth.getUser();if(!user||!roomId)return;const pending=profiles.some(p=>sel[p.id]?.label?.startsWith('Lainnya')&&!sel[p.id]?.other?.trim());const key=core.medical_record_no||core.doctor||core.event_id||core.service_stream||core.activity||null;const r=await sb.from('aureka_quality.quality_records').insert({room_id:roomId,profile_year:year,measurement_grain:grain,record_date:core.record_date||null,period_start:core.period_start||null,period_end:core.period_end||null,subject_key:key,subject_json:core,core_data:core,status:'ready',review_required:pending,entered_by:user.id}).select('*').single();if(r.error){setMsg(r.error.message);return}const obs=profiles.flatMap(p=>{const x=sel[p.id];if(!x?.label)return[];const o=(p.options_json||[]).find((z:any)=>z.label===x.label);return[{record_id:r.data.id,indicator_id:p.id,response_label:x.label,response_code:o?.code??null,raw_value:core,other_text:x.other||null,review_status:o?.code==null?'pending':'not_required'}]});if(obs.length){const o=await sb.from('aureka_quality.quality_record_responses').insert(obs);if(o.error){setMsg(o.error.message);return}}setSel({});setCore(coreFor(grain));setMsg(pending?'Tersimpan — menunggu klasifikasi superadmin untuk “Lainnya”.':'Data tersimpan.');load()}
 const archive=async(id:string)=>{const p=await sb.from('aureka_quality.quality_record_responses').select('id').eq('record_id',id).eq('review_status','pending');if((p.data||[]).length){setMsg('Baris ini masih menunggu klasifikasi superadmin.');return}const {data:{user}}=await sb.auth.getUser();if(!user)return;const e=await sb.from('aureka_quality.quality_records').update({status:'archived',validated_by:user.id,validated_at:new Date().toISOString(),archived_at:new Date().toISOString()}).eq('id',id);if(e.error)setMsg(e.error.message);else load()}
 return <div style={{display:'grid',gap:14}}><LiquidGlass style={{padding:14}}><div style={{display:'grid',gridTemplateColumns:isAdmin?'1fr 1fr':'1fr',gap:10}}>{isAdmin&&<label className="field" style={{margin:0}}><span>Unit</span><select value={roomId??''} onChange={e=>setRoomId(Number(e.target.value))}><option value="">Pilih unit</option>{rooms.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}<label className="field" style={{margin:0}}><span>Tahun</span><select value={year} onChange={e=>setYear(Number(e.target.value))}><option>2026</option><option>2027</option><option>2028</option></select></label></div></LiquidGlass><LiquidGlass style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div className="eyebrow">AUDIT INDIKATOR MUTU</div><h3 style={{margin:'4px 0',fontSize:24}}>Input Data</h3></div><span style={{fontSize:10,color:'var(--muted)'}}>{profiles.length} indikator · {grainLabel[grain]}</span></div>{msg&&<div className="msg visible" style={{color:'#0f7656'}}>{msg}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(260px,.55fr)',gap:16,marginTop:12}}><div style={{display:'grid',gap:9}}>{Object.entries(core).map(([k,v])=><label className="field" key={k} style={{margin:0}}><span>{k.replaceAll('_',' ')}</span><input value={v as any} onChange={e=>setCore((x:any)=>({...x,[k]:e.target.value}))}/></label>)}{profiles.map(p=>{const os=p.options_json||[];return os.length>1?<div key={p.id} style={{padding:'9px 0',borderTop:'1px solid rgba(20,34,27,.08)'}}><b style={{fontSize:11}}>{p.code} · {p.title||'(Tanpa judul)'}</b>{p.target_text&&<div style={{fontSize:9,color:'var(--muted)',margin:'3px 0 6px'}}>Target {p.target_text}</div>}<select value={sel[p.id]?.label||''} onChange={e=>setSel((x:any)=>({...x,[p.id]:{label:e.target.value,other:x[p.id]?.other||''}}))}><option value="">Pilih hasil</option>{os.map((o:any,i:number)=><option key={i} value={o.label}>{o.label}</option>)}</select>{sel[p.id]?.label?.startsWith('Lainnya')&&<input style={{marginTop:7}} placeholder="Alasan / temuan lainnya" value={sel[p.id]?.other||''} onChange={e=>setSel((x:any)=>({...x,[p.id]:{label:x[p.id]?.label,other:e.target.value}}))}/>}</div>:null})}<LiquidGlassButton className="wide" onClick={save}>Simpan Data</LiquidGlassButton></div><div style={{display:'grid',gap:8,alignContent:'start'}}><div className="eyebrow">REKAMAN</div>{records.map(r=><LiquidGlass key={r.id} style={{padding:11,borderRadius:16}}><b style={{fontSize:11}}>{r.subject_key||'Rekaman mutu'}</b><div style={{fontSize:9,color:'var(--muted)'}}>{r.record_date||r.created_at.slice(0,10)} · {r.review_required?'review':'siap'}</div><button className="textButton" onClick={()=>archive(r.id)}>✓ Valid dan arsipkan</button></LiquidGlass>)}</div></div></LiquidGlass></div>}
