create schema if not exists aureka_system;
create schema if not exists aureka_quality;
create schema if not exists aureka_patient_safety;
create schema if not exists aureka_risk;
create schema if not exists aureka_analytics;

create table if not exists public.master_rooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  is_active boolean not null default true,
  sort_order integer not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists aureka_system.app_roles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists aureka_system.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text,
  primary_room_id bigint references public.master_rooms(id),
  role_id uuid references aureka_system.app_roles(id),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists aureka_system.user_room_assignments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  room_id bigint not null references public.master_rooms(id),
  is_primary boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (user_id, room_id)
);

create table if not exists aureka_system.app_settings (
  key text primary key,
  value_json jsonb not null default '{}'::jsonb,
  description text,
  updated_at timestamptz not null default now()
);

create table if not exists aureka_system.module_registry (
  code text primary key,
  name text not null,
  description text,
  schema_name text,
  route text,
  is_active boolean not null default true,
  sort_order integer not null unique
);

insert into aureka_system.app_roles(code,name,description) values
('ADMIN','Administrator','Pengelola sistem dan konfigurasi AUREKA'),
('MANAGEMENT','Manajemen','Akses ringkasan dan pemantauan manajemen'),
('PIC','PIC Pelaporan','PIC unit/ruangan untuk pelaporan operasional'),
('PMKP','Komite PMKP','Pemantauan dan pengelolaan mutu rumah sakit')
on conflict (code) do update set name=excluded.name,description=excluded.description,is_active=true;

insert into aureka_system.module_registry(code,name,description,schema_name,route,sort_order) values
('overview','Overview','Dashboard publik dan role/unit based','aureka_system','/',0),
('quality_indicators','Indikator Mutu','Audit indikator mutu, Clinical Pathway, klinis & kematian, OPPE','aureka_quality','/indikator-mutu',1),
('patient_safety','Keselamatan Pasien','IKP, investigasi/RCA, survey budaya keselamatan pasien','aureka_patient_safety','/keselamatan-pasien',2),
('risk_management','Manajemen Risiko','Risk Register dan FMEA','aureka_risk','/manajemen-risiko',3),
('metadata_statistics','Metadata dan Statistik','Analitik statistik dan ekstraksi data','aureka_analytics','/metadata-statistik',4),
('settings','Pengaturan','Pengaturan umum dan manajemen user','aureka_system','/pengaturan',5)
on conflict (code) do update set name=excluded.name,description=excluded.description,schema_name=excluded.schema_name,route=excluded.route,is_active=true,sort_order=excluded.sort_order;

insert into public.master_rooms(code,name,sort_order) values
('INF_PENGADUAN','Informasi dan Pengaduan',1),('INFOTEK','Informatika dan Teknologi',2),('AMB','Instalasi Ambulance',3),('IBS','Instalasi Bedah Sentral',4),('FARM','Instalasi Farmasi',5),('IGD','Instalasi Gawat Darurat',6),('GIZI','Instalasi Gizi',7),('HD','Instalasi Hemodialisis',8),('LAB','Instalasi Laboratorium',9),('RAD','Instalasi Radiologi',10),('IRJ','Instalasi Rawat Jalan',11),('REHAB','Instalasi Rehab Medik',12),('RM','Instalasi Rekam Medis',13),('ICU_HCU','Intensive Care Unit & High Care Unit',14),('KOMED','Komite Medik',15),('PPI','Komite Pencegahan dan Pengendalian Infeksi',16),('MRS','Manajemen rumah Sakit',17),('NICU_PHDU','Neonatal Intensive Care Unit & Pediatrics High Dependency Unit',18),('NIFAS_OBGYN','Nifas Obstetrics & Gynecology',19),('PERINATOLOGI','Perinatology & Neonatology',20),('PKRS','Promosi Kesehatan Rumah Sakit',21),('RI_ANAK','Rawat Inap Anak',22),('RI_BEDAH','Rawat Inap Bedah',23),('RI_ISOLASI','Rawat Inap Isolasi',24),('RI_IPD','Rawat Inap Penyakit Dalam',25),('RI_SARAF','Rawat Inap Saraf',26),('RI_VIP','Rawat Inap VIP',27),('SPI','Satuan Pengawas Intern',28),('TIM_INVESTIGASI','Tim Investigasi',29),('TIM_PENDIDIKAN','Tim Koordinasi Pendidikan',30),('TIM_HIV','Tim Pelayanan Human Immunodeficiency Virus',31),('TIM_KB_RS','Tim Pelayanan Keluarga Berencana Rumah Sakit',32),('PONEK','Tim Pelayanan Obstetri Neonatal Emergensi Komprehensif',33),('ONKOLOGI','Tim Pelayanan Onkologi',34),('PPRA','Tim Pencegahan Resistensi Antimikroba',35),('TPKK','Tim Peningkatan Kinerja Klinis',36),('VERLOS','Verlos Kamer',37)
on conflict (code) do update set name=excluded.name,is_active=true,sort_order=excluded.sort_order;

alter table public.master_rooms enable row level security;
alter table aureka_system.app_roles enable row level security;
alter table aureka_system.user_profiles enable row level security;
alter table aureka_system.user_room_assignments enable row level security;
alter table aureka_system.app_settings enable row level security;
alter table aureka_system.module_registry enable row level security;
